### ISSUE TITLE
issues  with whmcs v8.6.2

### ISSUE THREAD

**Issue by stark131** [licson/beefyasian-pay#11]
Files are placed properly, inside the `include\hooks` and `modules`folder, however, this modules does not seem to be available on the panel. 
![screenshot](https://github.com/licson/beefyasian-pay/assets/74689799/d1ff6f66-4d78-4e80-920b-6636512d7cde)

**Comment by damonto** [comment]
You should try to activate the plugin at first 

https://docs.whmcs.com/Payment_Gateways#Activating_a_Payment_Gateway
