### ISSUE TITLE
WHMCS 8.2.1 不能正常使用

### ISSUE THREAD

**Issue by NSDCLOUD** [licson/beefyasian-pay#2]
<img width="1241" alt="截屏2021-09-24 上午12 35 28" src="https://user-images.githubusercontent.com/88206677/134548059-f844b141-e7b1-477b-9a4c-1e9a911e85c0.png">

**Comment by Joe-Ng-1998** [comment]
复制的时候要连同子目录一起。

**Comment by SeonMe** [comment]
> 复制的时候要连同子目录一起。

确实 8.2.1 无法使用，提示未激活，之后无法找到配置文件。
