### ISSUE TITLE
If the payment does not complete address will stay on hold?

### ISSUE THREAD

**Issue by Al-Bsharat** [licson/beefyasian-pay#8]
Hello Dear Support.
Now if the customer do not pay an invoice the address will never unlocked again? (I will lose it)

Thanks

**Comment by damonto** [comment]
If the customer do not pay an invoice the address will be released after 30 minutes. You can change the timeout value on the whmcs dashboard. If the invoice is not fully paid the address will be automatically renew until it's fully paid.

**Comment by Al-Bsharat** [comment]
Got it.
Thank you for your great support.
